python main.py --dataset=mind-f --model=KGAT --mode=full  --lrate=0.01 --embedding_size=32 --weight_decay=1e-3 --reg=0.01
python main.py --dataset=mind-f --model=KGAT --mode=full  --lrate=0.01 --embedding_size=32 --weight_decay=1e-4 --reg=0.01
python main.py --dataset=mind-f --model=KGAT --mode=full  --lrate=0.01 --embedding_size=32 --weight_decay=1e-5 --reg=0.01
python main.py --dataset=mind-f --model=KGAT --mode=full  --lrate=0.01 --embedding_size=64 --weight_decay=5e-4 --reg=0.0001
python main.py --dataset=mind-f --model=KGAT --mode=full  --lrate=0.01 --embedding_size=64 --weight_decay=5e-5 --reg=0.001
python main.py --dataset=mind-f --model=KGAT --mode=full  --lrate=0.01 --embedding_size=128 --weight_decay=1e-5 --reg=0.001
python main.py --dataset=alibaba-fashion --model=KGAT --mode=full  --lrate=0.01 --embedding_size=32 --weight_decay=1e-3 --reg=0.01
python main.py --dataset=alibaba-fashion --model=KGAT --mode=full  --lrate=0.01 --embedding_size=32 --weight_decay=1e-4 --reg=0.01
python main.py --dataset=alibaba-fashion --model=KGAT --mode=full  --lrate=0.01 --embedding_size=32 --weight_decay=1e-5 --reg=0.01
python main.py --dataset=alibaba-fashion --model=KGAT --mode=full  --lrate=0.01 --embedding_size=64 --weight_decay=5e-4 --reg=0.0001
python main.py --dataset=alibaba-fashion --model=KGAT --mode=full  --lrate=0.01 --embedding_size=64 --weight_decay=5e-5 --reg=0.001
python main.py --dataset=alibaba-fashion --model=KGAT --mode=full  --lrate=0.01 --embedding_size=128 --weight_decay=1e-5 --reg=0.001